server:
  port: 8189
  servlet:
    context-path: /app
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/geek_db
#    url: jdbc:mysql://127.0.0.1:3306/geek_db?allowPublicKeyRetrieval=true&useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: zW0OWm2t8o04AKXFbRNV
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
#  h2:
#    console:
#      enabled: true
#      settings:
#        web-allow-others: false